import '@/styles/globals.css'
import Content from '@/components/Layout/Content';
import NavigationMenu from '@/components/Layout/NavigationMenu';
import { BrowserRouter as Router, Routes, Route } from 'react-router-dom';
import Company from './company';
import Contacts from './contacts';
import Home from './home';
import NewProject from './newProject';
import { useEffect, useState } from 'react';
import Head from 'next/head';

/* const isBrowser = typeof window !== 'undefined'; */

export default function AppHome() {
  const [isBrowser, setIsBrowser] = useState(false);
  useEffect(() => {
    setIsBrowser(typeof window !== 'undefined');
  }, []);
  return isBrowser ? (
    <>
    <Head>
        <title>Taylor Dashboard</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Router>
        <NavigationMenu />
        <Content>
          <Routes>
            <Route path="/" element={<Home />} />
            <Route path="/company" element={<Company />} />
            <Route path="/contacts" element={<Contacts />} />
            <Route path="/newProject" element={<NewProject />} />
          </Routes>
        </Content>
      </Router>
    </>
  ) : null;
}
